# Generated by Django 2.1.7 on 2019-05-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('head0', models.CharField(default='', max_length=300)),
                ('head1', models.CharField(default='', max_length=300)),
                ('head2', models.CharField(default='', max_length=300)),
                ('pub_date', models.DateField(default='')),
                ('thumbnail', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
